// ========== 主 MSG_TYPE 枚举 ==========
export const APP_MSG_TYPE_DICT: Record<number, string> = {
  0: "MSG_TYPE_BT",
  1: "MSG_TYPE_CONN",
  2: "MSG_TYPE_WWS",
  3: "MSG_TYPE_EVT",
  4: "MSG_TYPE_AUDIO",
  5: "MSG_TYPE_TONE",
  6: "MSG_TYPE_CHARGER",
  7: "MSG_TYPE_BAT",
  8: "MSG_TYPE_BTN",
  9: "MSG_TYPE_LED",
  10: "MSG_TYPE_PM",
  11: "MSG_TYPE_INEAR",
  12: "MSG_TYPE_USR_CFG",
  13: "MSG_TYPE_ECONN",
  14: "MSG_TYPE_CLI",
  15: "MSG_TYPE_OTA",
  16: "MSG_TYPE_SYNC",
  17: "MSG_TYPE_MAIN",
  18: "MSG_TYPE_LOOPBACK",
  19: "MSG_TYPE_RECORDSV",
  20: "MSG_TYPE_LOG_DUMP",
  21: "MSG_TYPE_LEA_AUDIO",
  22: "MSG_TYPE_SYNC_SPP",
  23: "MSG_TYPE_SYNC_BLE",
  24: "MSG_TYPE_SYNC_IAP2",
  25: "MSG_TYPE_SPATIAL",
  26: "MSG_TYPE_AUDIO_ANC",
  27: "MSG_TYPE_GATTC",
  28: "MSG_TYPE_VAD",
  29: "MSG_TYPE_GFPS",
  30: "MSG_TYPE_AUDIO_LOCAL_MUSIC",
  31: "MSG_TYPE_ALARM",
  32: "MSG_TYPE_IAP2",
  33: "MSG_TYPE_VIRTUAL_BASS",
  34: "MSG_TYPE_ADEQ",
  35: "MSG_TYPE_DRC",
  36: "MSG_TYPE_EQ",
  37: "MSG_TYPE_CUS_TRANS",
  38: "MSG_TYPE_IMU",
  39: "MSG_TYPE_TOUCH",
  40: "MSG_TYPE_USER_BTN",
  41: "MSG_TYPE_FACTORY_TEST",
  42: "MSG_TYPE_CUS_LIB1",
  43: "MSG_TYPE_CUS_LIB2",
  44: "MSG_TYPE_CUS_LIB3",
  45: "MSG_TYPE_CUS_LIB4",
  46: "MSG_TYPE_CUS_LIB5",
  47: "MSG_TYPE_CUS_LIB6",
  48: "MSG_TYPE_CUS_LIB7",
  49: "MSG_TYPE_CUS_LIB8",
  50: "MSG_TYPE_MAX",
};

// ========== 完整的 MSG_ID 映射表 ==========
export const MSG_ID_MAP: Record<string, Record<number, string>> = {
  // ===== MSG_TYPE_IMU (38) =====
  "MSG_TYPE_IMU": {
    1: "IMU_MSG_ID_SET_SLAVE_UPLOAD_ONOFF",
    2: "IMU_MSG_ID_SLAVE_SEND_IMU_DATA_TO_MASTER",
    3: "IMU_MSG_ID_WEAR_EVENT",
    4: "IMU_MSG_ID_GET_IMU_DATA",
    5: "IMU_MSG_ID_TEAMING_R_SYNC_EARPHONE_STATUS_TO_TEAMING_L",
    6: "IMU_MSG_ID_TEAMING_L_SYNC_EARPHONE_STATUS_TO_TEAMING_R",
    7: "IMU_MSG_ID_TEAMING_R_FREEFALL_NOTIFICATION",
    8: "IMU_MSG_ID_LET_MASTER_NOTIFY_APP_FREEFALL_EVENT",
    9: "IMU_MSG_ID_PLAY_FREEFALL_TONE",
    10: "IMU_MSG_ID_SEND_SYNC_STATUS",
  },

  // ===== MSG_TYPE_BT (0) =====
  "MSG_TYPE_BT": {
    1000: "APP_BT_MSG_ID_CONNECT_SCO",
    1001: "APP_BT_MSG_ID_SYNC_CALL_VOLUME",
    1002: "APP_BT_MSG_ID_SYNC_MUSIC_VOLUME",
    1003: "APP_BT_MSG_ID_CONNECT_AUTO_PLAY",
    1004: "APP_BT_MSG_ID_REPORT_BATTERY_AND_CALL_VOLUME",
    1005: "APP_BT_MSG_ID_SYNC_GA_VOLUME",
    // Remote data (1000 + 0x80 = 1128)
    1128: "APP_BT_MSG_ID_REMOTE_DATA_WWS_SYNC",
    1129: "APP_BT_MSG_ID_REMOTE_DATA_GA_STATE",
    1130: "APP_BT_MSG_ID_REMOTE_DATA_CONN_PREEMPTIVE",
    1131: "APP_BT_MSG_ID_REMOTE_DATA_LE_AUDIO_ADV_REQ",
    1132: "APP_BT_MSG_ID_REMOTE_DATA_VISIBILITY",
    1133: "APP_BT_MSG_ID_REMOTE_DATA_ADD_PAIRED_DEVICE",
    1134: "APP_BT_MSG_ID_REMOTE_DATA_REMOVE_PAIRED_DEVICE",
    1135: "APP_BT_MSG_ID_REMOTE_DATA_GET_RSSI_REQ",
    1136: "APP_BT_MSG_ID_REMOTE_DATA_GET_RSSI_RSP",
  },

  // ===== MSG_TYPE_CONN (1) =====
  "MSG_TYPE_CONN": {
    1: "CONN_MSG_ID_POWER_ON_CONNECT",
    2: "CONN_MSG_ID_RECONNECT",
    3: "CONN_MSG_ID_REMOTE_AUTO_CONNECT_DONE",
    4: "CONN_MSG_ID_REMOTE_SYNC_LIST",
    5: "CONN_MSG_ID_POWER_ON_RECONNECT_TIMEOUT",
    6: "CONN_MSG_ID_GATT_CONNECT",
    7: "CONN_MSG_ID_LINKLOSS_TIMEOUT",
    // Remote data (0x80 = 128)
    128: "CONN_MSG_ID_REMOTE_DATA_WWS_SYNC",
    129: "CONN_MSG_ID_REMOTE_SET_GATT_BREDR",
  },

  // ===== MSG_TYPE_WWS (2) =====
  "MSG_TYPE_WWS": {
    0: "APP_WWS_MSG_ID_TRIGGER_ROLE_SWITCH",
    1: "APP_WWS_MSG_ID_RSSI_DETECT",
    2: "APP_WWS_MSG_ID_REPORT_CONNECTED",
    3: "APP_WWS_MSG_ID_RECV_DATA",
  },

  // ===== MSG_TYPE_EVT (3) =====
  "MSG_TYPE_EVT": {
    // --- 用户事件 (User Events) 1000-1068 ---
    1000: "EVTUSR_POWER_ON",
    1001: "EVTUSR_POWER_OFF",
    1002: "EVTUSR_FACTORY_RESET",
    1003: "EVTUSR_CLEAR_PDL",
    1004: "EVTUSR_START_WWS_PAIR",
    1005: "EVTUSR_WWS_ROLE_SWITCH",
    1006: "EVTUSR_ENTER_PAIRING",
    1007: "EVTUSR_CANCEL_PAIRING",
    1008: "EVTUSR_CONNECT_LAST",
    1009: "EVTUSR_VOICE_TRANSFER_TOGGLE",
    1010: "EVTUSR_VOICE_RECOGNITION_TOGGLE",
    1011: "EVTUSR_REDIAL_LAST",
    1012: "EVTUSR_ANSWER",
    1013: "EVTUSR_REJECT",
    1014: "EVTUSR_HANGUP",
    1015: "EVTUSR_THREE_WAY_REJECT_WAITING",
    1016: "EVTUSR_THREE_WAY_RELEASE_ACTIVE_ACCEPT_HELD_WAITING",
    1017: "EVTUSR_THREE_WAY_HOLD_ACTIVE_ACCEPT_HELD_WAITING",
    1018: "EVTUSR_AUDIO_PROMPT_LANGUAGE_TOGGLE",
    1019: "EVTUSR_MUSIC_PLAY_PAUSE",
    1020: "EVTUSR_MUSIC_PLAY",
    1021: "EVTUSR_MUSIC_PAUSE",
    1022: "EVTUSR_MUSIC_STOP",
    1023: "EVTUSR_MUSIC_FORWARD",
    1024: "EVTUSR_MUSIC_BACKWARD",
    1025: "EVTUSR_VOLUME_UP",
    1026: "EVTUSR_VOLUME_DOWN",
    1027: "EVTUSR_MIC_MUTE",
    1028: "EVTUSR_MIC_UNMUTE",
    1029: "EVTUSR_MIC_MUTE_TOGGLE",
    1030: "EVTUSR_SPK_MUTE",
    1031: "EVTUSR_SPK_UNMUTE",
    1032: "EVTUSR_SPK_MUTE_TOGGLE",
    1033: "EVTUSR_USER_EQ_ON",
    1034: "EVTUSR_USER_EQ_OFF",
    1035: "EVTUSR_USER_EQ_TOGGLE",
    1036: "EVTUSR_LISTEN_MODE_TOGGLE",
    1037: "EVTUSR_ENTER_FACTORY_TEST_MODE",
    1038: "EVTUSR_ENTER_OTA_MODE",
    1039: "EVTUSR_ENTER_AUDIO_TEST_MODE",
    1040: "EVTUSR_CUSTOM_1",
    1041: "EVTUSR_CUSTOM_2",
    1042: "EVTUSR_CUSTOM_3",
    1043: "EVTUSR_CUSTOM_4",
    1044: "EVTUSR_CUSTOM_5",
    1045: "EVTUSR_CUSTOM_6",
    1046: "EVTUSR_CUSTOM_7",
    1047: "EVTUSR_CUSTOM_8",
    1048: "EVTUSR_GAME_MODE_TOGGLE",
    1049: "EVTUSR_FACTORY_RESET_KEEP_WWS",
    1050: "EVTUSR_ENTER_DUT_MODE",
    1051: "EVTUSR_USER_INEAR_ENABLE_TOGGLE",
    1052: "EVTUSR_VOICE_RECOGNITION_ACTIVATE",
    1053: "EVTUSR_VOICE_RECOGNITION_DEACTIVATE",
    1054: "EVTUSR_ENTER_SHIPPING_MODE",
    1055: "EVTUSR_SIDE_TONE_TOGGLE",
    1056: "EVTUSR_REBOOT",
    1057: "EVTUSR_ADAPTIVE_ANC_TOGGLE",
    1058: "EVTUSR_VOICE_RECOGNITION_RESTARTED",
    1059: "EVTUSR_LOOPBACK_STREAM_TOGGLE",
    1060: "EVTUSR_ADAPTIVE_ANC_START",
    1061: "EVTUSR_ADAPTIVE_ANC_STOP",
    1062: "EVTUSR_MANC_START",
    1063: "EVTUSR_MANC_STOP",
    1064: "EVTUSR_HID_CMD_VOLUME_UP",
    1065: "EVTUSR_HID_CMD_VOLUME_DOWN",
    1066: "EVTUSR_HID_CMD_ZOOM_IN",
    1067: "EVTUSR_HID_CMD_ZOOM_OUT",
    1068: "EVTUSR_LAST",
    // --- 系统事件 (System Events) 8000-8087 ---
    8000: "EVTSYS_BT_INITED",
    8001: "EVTSYS_STATE_CHANGED",
    8002: "EVTSYS_CONNECTED",
    8003: "EVTSYS_DISCONNECTED",
    8004: "EVTSYS_LINK_LOSS",
    8005: "EVTSYS_SCOLINK_OPEN",
    8006: "EVTSYS_SCOLINK_CLOSE",
    8007: "EVTSYS_VOICE_RECOGNITION_START",
    8008: "EVTSYS_VOICE_RECOGNITION_STOP",
    8009: "EVTSYS_RING",
    8010: "EVTSYS_CALL_END",
    8011: "EVTSYS_WWS_CONNECTED",
    8012: "EVTSYS_WWS_DISCONNECTED",
    8013: "EVTSYS_WWS_ROLE_SWITCH",
    8014: "EVTSYS_CHARGE_COMPLETE",
    8015: "EVTSYS_PUT_IN",
    8016: "EVTSYS_TAKE_OUT",
    8017: "EVTSYS_BATTERY_LOW",
    8018: "EVTSYS_BATTERY_LEVEL_CHANGED",
    8019: "EVTSYS_VOLUME_MAX",
    8020: "EVTSYS_VOLUME_MIN",
    8021: "EVTSYS_MUSIC_VOLUME_CHANGED",
    8022: "EVTSYS_CALL_VOLUME_CHANGED",
    8023: "EVTSYS_CMC_BOX_OPEN",
    8024: "EVTSYS_CMC_BOX_CLOSE",
    8025: "EVTSYS_CMC_LONG_3S",
    8026: "EVTSYS_CMC_LONG_10S",
    8027: "EVTSYS_CMC_LONG_20S",
    8028: "EVTSYS_WWS_PAIRED",
    8029: "EVTSYS_WWS_PAIR_FAILED",
    8030: "EVTSYS_IN_EAR",
    8031: "EVTSYS_OUT_OF_EAR",
    8032: "EVTSYS_LISTEN_MODE_NORMAL",
    8033: "EVTSYS_LISTEN_MODE_ANC",
    8034: "EVTSYS_LISTEN_MODE_TRANSPARENT",
    8035: "EVTSYS_BT_POWER_ON",
    8036: "EVTSYS_BT_POWER_OFF",
    8037: "EVTSYS_ENTER_PAIRING",
    8038: "EVTSYS_BUTTON_PRESS",
    8039: "EVTSYS_INEAR_ENABLE",
    8040: "EVTSYS_INEAR_DISABLE",
    8041: "EVTSYS_CUSTOM_1",
    8042: "EVTSYS_CUSTOM_2",
    8043: "EVTSYS_CUSTOM_3",
    8044: "EVTSYS_CUSTOM_4",
    8045: "EVTSYS_CUSTOM_5",
    8046: "EVTSYS_CUSTOM_6",
    8047: "EVTSYS_CUSTOM_7",
    8048: "EVTSYS_CUSTOM_8",
    8049: "EVTSYS_POWER_ON_RECONNECT_FAILED",
    8050: "EVTSYS_LINK_LOSS_RECONNECT_FAILED",
    8051: "EVTSYS_FACTORY_RESET_DONE",
    8052: "EVTSYS_BOX_CMD_POWER_OFF",
    8053: "EVTSYS_BOX_CMD_REBOOT",
    8054: "EVTSYS_BOX_CMD_BT_DISABLE",
    8055: "EVTSYS_AUTO_POWER_OFF",
    8056: "EVTSYS_GAME_MODE_ON",
    8057: "EVTSYS_GAME_MODE_OFF",
    8058: "EVTSYS_BAT_LOW_POWER_OFF",
    8059: "EVTSYS_BUTTON_SINGLE",
    8060: "EVTSYS_BUTTON_DOUBLE",
    8061: "EVTSYS_BUTTON_LONG",
    8062: "EVTSYS_BUTTON_VLONG",
    8063: "EVTSYS_BUTTON_RELEASE",
    8064: "EVTSYS_PAIR_REMOVED",
    8065: "EVTSYS_A2DP_DISCONNECTED",
    8066: "EVTSYS_HFP_DISCONNECTED",
    8067: "EVTSYS_LISTEN_MODE_AA",
    8068: "EVTSYS_LISTEN_MODE_TT",
    8069: "EVTSYS_SIDE_TONE_ENABLED",
    8070: "EVTSYS_SIDE_TONE_DISABLED",
    8071: "EVTSYS_A2DP_CONNECTED",
    8072: "EVTSYS_HFP_CONNECTED",
    8073: "EVTSYS_BUTTON_TRIPLE",
    8074: "EVTSYS_ENTER_DUT_MODE",
    8075: "EVTSYS_HFP_EXT_AT_REPORT",
    8076: "EVTSYS_FIND_ME",
    8077: "EVTSYS_DLY_MD_REPORT",
    8078: "EVTSYS_BUTTON_SLIDE_UP",
    8079: "EVTSYS_BUTTON_SLIDE_DOWN",
    8080: "EVTSYS_LEAK_ANC_START",
    8081: "EVTSYS_FIT_TEST_START",
    8082: "EVTSYS_TONE_DETECT_START",
    8083: "EVTSYS_OTA_START",
    8084: "EVTSYS_OTA_STOP",
    8085: "EVTSYS_TEST_MODE_ENTER",
    8086: "EVTSYS_TEST_MODE_EXIT",
    8087: "EVTSYS_LAST",
  },

  // ===== MSG_TYPE_AUDIO (4) =====
  "MSG_TYPE_AUDIO": {
    // 本地音频消息
    0: "APP_AUDIO_MSG_ID_FIT_TEST_RESULT",
    1: "APP_AUDIO_MSG_ID_SIDE_TONE_SWITCH_DONE",
    2: "APP_AUDIO_MSG_ID_ENV_NOISE_DETECT_CFG",
    3: "APP_AUDIO_MSG_ID_ENV_NOISE_DETECT_VOL_UPDATE",
    4: "APP_AUDIO_MSG_ID_LOOPBACK_MODE_SET",
    5: "APP_AUDIO_MSG_ID_SYNC_SPATIAL_AUDIO",
    6: "APP_AUDIO_MSG_ID_MUSIC_VOLUME_CHANGE",
    7: "APP_AUDIO_MSG_ID_CALL_VOLUME_CHANGE",
    8: "APP_AUDIO_MSG_ID_REQ_UPDATE_VOLUME",
    9: "APP_AUDIO_MSG_ID_SYNC_UPDATE_VOLUME",
    10: "APP_AUDIO_MSG_ID_RESET_FIRST_VOL_CHANGE",
    11: "APP_AUDIO_MSG_ID_SYNC_HEARING_PROTECT",
    12: "APP_AUDIO_MSG_ID_TALK_CHECK_RESULT",
    13: "APP_AUDIO_MSG_ID_FIT_TEST_SET_PARAM",
    14: "APP_AUDIO_MSG_ID_SYNC_FIT_TEST_START",
    15: "APP_AUDIO_MSG_ID_HEARING_PROTECT_SET_MD",
    16: "APP_AUDIO_MSG_ID_AUD_SV_EVT_RPT",
    17: "APP_AUDIO_MSG_ID_SET_END_CFG",
    18: "APP_AUDIO_MSG_ID_SYNC_SET_END_CFG",
    19: "APP_AUDIO_MSG_ID_END_ENABLE",
    20: "APP_AUDIO_MSG_ID_SYNC_END_ENABLE",
    21: "APP_AUDIO_MSG_ID_TONE_PLAYING",
    // 远程同步数据 (0x80 = 128)
    128: "APP_AUDIO_MSG_ID_REMOTE_DATA_WWS_SYNC",
    129: "APP_AUDIO_MSG_ID_REMOTE_DATA_VOLUME",
    130: "APP_AUDIO_MSG_ID_REMOTE_DATA_VOLUME_MUSIC",
    131: "APP_AUDIO_MSG_ID_REMOTE_DATA_VOLUME_CALL",
    132: "APP_AUDIO_MSG_ID_REMOTE_DATA_TDS_VOLUME_SYNC_REQ",
    133: "APP_AUDIO_MSG_ID_REMOTE_DATA_GAME_MODE",
    134: "APP_AUDIO_MSG_ID_REMOTE_DATA_MIC_MUTE_STATE",
    135: "APP_AUDIO_MSG_ID_REMOTE_DATA_SIDE_TONE_STATE",
    136: "APP_AUDIO_MSG_ID_REMOTE_DATA_GA_VOLUME",
    137: "APP_AUDIO_MSG_ID_REMOTE_DATA_ENV_NOISE_DETECT_ENABLE",
    138: "APP_AUDIO_MSG_ID_REMOTE_DATA_LOOPBACK_MODE_SET",
    139: "APP_AUDIO_MSG_ID_REMOTE_DATA_MUSIC_MUTE",
  },

  // ===== MSG_TYPE_TONE (5) =====
  "MSG_TYPE_TONE": {
    0: "TONE_MESSAGE_ID_INIT",
    1: "TONE_MESSAGE_ID_DONE",
    2: "TONE_MESSAGE_ID_DO_PLAY_TONE",
    3: "TONE_MESSAGE_ID_PLAY_SYNC_INFO",
    4: "TONE_MESSAGE_ID_LOCAL_MEET_SYNC_INFO",
    5: "TONE_MESSAGE_ID_SYNC_SET_LANGUAGE",
    6: "TONE_MESSAGE_ID_SYNC_SET_THEME",
  },

  // ===== MSG_TYPE_CHARGER (6) =====
  "MSG_TYPE_CHARGER": {
    0x80: "CHARGER_MSG_ID_REMOTE_DATA_IN_BOX",
    0x81: "CHARGER_MSG_ID_REMOTE_DATA_WWS_SYNC",
    0x82: "CHARGER_MSG_ID_REMOTE_DATA_BOX_STATE",
  },

  // ===== MSG_TYPE_BAT (7) =====
  "MSG_TYPE_BAT": {
    0x00: "BAT_MSG_ID_LOW",
    0x01: "BAT_MSG_ID_FULL",
    0x02: "BAT_MSG_ID_LEVEL",
    0x80: "BAT_MSG_ID_REMOTE_DATA_WWS_SYNC",
    0x81: "BAT_MSG_ID_REMOTE_DATA_BATTERY",
  },

  // ===== MSG_TYPE_BTN (8) =====
  "MSG_TYPE_BTN": {
    0x01: "APP_BTN_MSG_ID_KEY_CALLBACK",
    0x02: "APP_BTN_MSG_ID_KEY_OPEN",
    0x80: "APP_BTN_MSG_ID_REMOTE_DATA_SET_KEY_CONFIG",
    0x81: "APP_BTN_MSG_ID_REMOTE_DATA_RESET_KEY_CONFI",
  },

  // ===== MSG_TYPE_LED (9) =====
  "MSG_TYPE_LED": {},

  // ===== MSG_TYPE_PM (10) =====
  "MSG_TYPE_PM": {
    0: "PM_MSG_ID_POWER_ON",
    1: "PM_MSG_ID_POWER_OFF",
    2: "PM_MSG_ID_AUTO_POWER_OFF",
    3: "PM_MSG_ID_POWER_OFF_DONE",
    4: "PM_MSG_ID_FORCE_POWER_OFF_DONE",
    5: "PM_MSG_ID_SYNC_POWER_OFF",
    6: "PM_MSG_ID_ENABLE_POWER_OFF",
  },

  // ===== MSG_TYPE_INEAR (11) =====
  "MSG_TYPE_INEAR": {},

  // ===== MSG_TYPE_USR_CFG (12) =====
  "MSG_TYPE_USR_CFG": {
    0x01: "USR_CFG_MSG_ID_SAVE_CFG",
    0x80: "USR_CFG_MSG_ID_REMOTE_DATA_RESET_PDL",
  },

  // ===== MSG_TYPE_ECONN (13) =====
  "MSG_TYPE_ECONN": {
    1: "ECONN_MSG_ID_FACTORY_RESET",
    2: "ECONN_REMOTE_MSG_ID_BTN_RESET",
    3: "ECONN_REMOTE_MSG_ID_UPDATE_AUTO_POWER_OFF",
    4: "ECONN_REMOTE_MSG_ID_UPDATE_EQ",
    5: "ECONN_REMOTE_MSG_ID_UPDATE_BTN",
    6: "ECONN_REMOTE_MSG_ID_UPDATE_TOUCH_TONE",
    7: "ECONN_REMOTE_MSG_ID_DELIVER_CMD",
    8: "ECONN_MSG_ID_FORCE_DISCOVERABLE",
    9: "ECONN_MSG_ID_RESTART_AUTO_POWER_OFF",
    10: "ECONN_MSG_ID_CLAER_LAST_BATTERY_LOW",
    11: "ECONN_MSG_ID_REPORT_TWS_STATE",
    13: "ECONN_REMOTE_MSG_ID_GET_UI_STATISTICS",
    14: "ECONN_REMOTE_MSG_ID_GET_UI_STATISTICS_RSP",
    15: "ECONN_REMOTE_MSG_ID_CLAER_UI_STATISTICS",
    16: "ECONN_REMOTE_MSG_ID_REPORT_COLOR",
    17: "ECONN_REMOTE_MSG_ID_UPDATE_COLOR",
    18: "ECONN_REMOTE_MSG_ID_UPDATE_GAME_MODE",
    19: "ECONN_REMOTE_MSG_ID_SYNC_ECONN_CFG",
    20: "ECONN_MSG_ID_BOX_CLOSE_CHG_LIMIT_TIMEOUT",
    21: "ECONN_MSG_ID_UPDATE_EQ_ANTI_SHAKE",
    22: "ECONN_REMOTE_MSG_ID_UPDATE_SIDE_TONE",
    23: "ECONN_REMOTE_MSG_ID_START_WEAR_FIT_DETECT",
    24: "ECONN_REMOTE_MSG_ID_WEAR_FIT_DETECT_RESULT",
    25: "ECONN_MSG_ID_WEAR_FIT_DETECT_RESULT",
    26: "ECONN_MSG_ID_2RD_DEVICE_PAIRING",
    27: "ECONN_MSG_ID_2RD_PAIRING_TIMEOUT",
    28: "ECONN_MSG_ID_LDAC_ON_OFF",
    29: "ECONN_MSG_ID_PDL_ON_OFF",
    30: "ECONN_MSG_ID_REPORT_PDL_FRAME",
    31: "ECONN_MSG_ID_REPORT_DISCONN_RESULT",
    32: "ECONN_MSG_ID_REPORT_CONN_RESULT",
    33: "ECONN_MSG_ID_DISCONNECT_OR_CONNECT_SCO",
    34: "ECONN_MSG_ID_DELAY_WRITE_KV",
    35: "ECONN_MSG_ID_ENTER_SHIPPING_MODE",
    36: "ECONN_MSG_ID_ENTER_DUT_MODE",
    37: "ECONN_MSG_ID_CHARGER_OUT_ROLE",
    38: "ECONN_REMOTE_MSG_ID_UPDATE_SPATIAL_AUDIO",
    39: "ECONN_REMOTE_MSG_ID_UPDATE_HEARING_PROTECT",
    40: "ECONN_REMOTE_MSG_ID_HEARING_DETEC_ENABLE",
    41: "ECONN_REMOTE_MSG_ID_HEARING_DETEC_CFG_VOL",
    42: "ECONN_REMOTE_MSG_ID_HEARING_DETEC_CFG_FREQ",
    43: "ECONN_COMM_FROM_APP",
    44: "ECONN_COMM_FROM_MSG",
    45: "ECONN_SLAVE_APPINFO",
    46: "ECONN_MULTI_PAIR_EXIT",
    47: "ECONN_MASTER_STATUS",
    48: "ECONN_MSG_ID_DELAY_LINK_LOSS_WAV",
    49: "ECONN_MSG_ID_CANCEL_RECONNECT",
    50: "ECONN_REMOTE_MSG_ID_CONN_LED",
    51: "ECONN_MSG_ID_DELAY_PLAY_TONE_CONNECTED",
    52: "ECONN_MSG_ID_CHECK_SPP_STATE",
    53: "ECONN_MSG_ID_SYNC_NAME_LIST",
    54: "ECONN_MSG_DUAL_PRI_DETECT_REC_B",
    55: "ECONN_MSG_ID_SYNC_APP_GATTS_CONN_STATE",
    56: "ECONN_MSG_ID_DELAY_SET_OTA_SCAN",
    // Anker custom
    104: "ANKER_MSG_ID_PREEMPTION_START",
    105: "ANKER_MSG_ID_PREEMPTION_DELAY",
    106: "ECONN_MSG_ID_IPHONE_CONNECT_SCO",
    107: "ECONN_MSG_ID_AGING_AUDIO_TONE",
    108: "ECONN_REMOTE_AGING_AUDIO_PTTEST_ON",
    110: "ECONN_MSG_ID_MAIDAN_STORAGE",
    111: "ECONN_MSG_ID_APP_SETUP",
    112: "ECONN_MSG_ID_APP_RSP_INFO",
    113: "ECONN_MSG_ID_LDAC_PALYSTATUS",
    114: "ECONN_MSG_ID_OTA_START",
    115: "ECONN_MSG_ENTEY_PAIRING",
    116: "ECONN_MSG_ENTEY_RECONNECTING",
    117: "ECONN_MSG_UPDATE_PHONENAME",
    118: "ECONN_MSG_BALANCE_UPDATE",
    119: "ECONN_MSG_reconnect_after_pdl_sync",
    120: "ECONN_MSG_reconnect_after_pdl_sync0",
    121: "ECONN_MSG_ID_SET_FIND_ME_TONE",
    122: "ECONN_MSG_ID_LOOPPLAY_FIND_ME_TONE",
    123: "ECONN_MSG_ID_SYNC_CANCEL_FIND_ME_TONE",
    124: "ECONN_MSG_ID_APP_RSP_TRACKER_INFO",
    125: "ECONN_MSG_ID_ROLE_FIND_ME_TONE",
    126: "ECONN_MSG_ID_MFICONN_ROLE_DELAY",
    138: "ECONN_REMOTE_MSG_ID_DELAY_MFI_CONN",
    145: "ECONN_REMOTE_MSG_ID_DELAY_MFI_DISCONN",
    149: "ECONN_REMOTE_MSG_SYNC_IAP2_ADDR",
    150: "ECONN_MSG_ID_DELAY_ECONN_HANDLE_DATA",
    151: "ECONN_MSG_ID_RETRY_CONNECT_BY_MAC",
    152: "ECONN_MSG_ID_RECONNECT_FAILED_REPORT",
    153: "ECONN_MSG_ID_TWS_DISCONNECT_DETSCT_ENABLE",
    154: "ECONN_MSG_ID_DELAY_SEND_KILL_BLACKGROUND_PROCESSES",
    155: "ECONN_MSG_ID_SAVE_DREAM_APP_PALYER",
    156: "ECONN_MSG_ID_TWS_ROLE_CHANGE_VAD_CHECK",
    157: "ECONN_MSG_ID_TWS_UI_WEAR_STATUS_SYN",
    158: "ECONN_MSG_ID_TWS_UI_PEER_WEAR_STATUS",
    159: "ECONN_MSG_ID_TWS_UI_WEAR_PAUSE_FLAG_UPDATA",
    160: "ECONN_MSG_ID_TWS_CONNECT_CHECK_MASTER_SLAVE",
    161: "ECONN_MSG_ID_KEYLIST_ERROR_DELAY_RETRY",
    163: "ECONN_MSG_ID_CHANGE_VAD_SWITCH_DELAY",
  },

  // ===== MSG_TYPE_CLI (14) =====
  "MSG_TYPE_CLI": {},

  // ===== MSG_TYPE_OTA (15) =====
  "MSG_TYPE_OTA": {
    0: "OTA_MSG_ID_TASK_FINISH",
    1: "OTA_MSG_ID_TASK_STARTED",
    2: "OTA_MSG_ID_ROLE_SWITCH",
    3: "OTA_MSG_ID_REBOOT",
    4: "OTA_MSG_ID_CHECK_UPDATEING_TIMEOUT",
    5: "OTA_MSG_ID_REMOTE_TASK_STARTED",
    6: "OTA_MSG_ID_REMOTE_SYNC_FILE_CRC",
  },

  // ===== MSG_TYPE_SYNC (16) =====
  "MSG_TYPE_SYNC": {
    1: "OTA_SYNC_MSG_ID_GET_DATA",
    2: "OTA_SYNC_MSG_ID_STOP",
    3: "OTA_SYNC_MSG_ID_DO_REBOOT",
    4: "OTA_SYNC_REMOTE_MSG_ID_START",
    5: "OTA_SYNC_REMOTE_MSG_ID_STOP",
    6: "OTA_SYNC_REMOTE_MSG_ID_REBOOT",
    7: "OTA_SYNC_REMOTE_MSG_ID_GET_DATA_REQ",
    8: "OTA_SYNC_REMOTE_MSG_ID_GET_DATA_RSP",
    9: "OTA_SYNC_REMOTE_MSG_ID_DONE_REPORT",
    10: "OTA_SYNC_MSG_ID_VERIFY_DONE",
  },

  // ===== MSG_TYPE_MAIN (17) =====
  "MSG_TYPE_MAIN": {},

  // ===== MSG_TYPE_LOOPBACK (18) =====
  "MSG_TYPE_LOOPBACK": {},

  // ===== MSG_TYPE_RECORDSV (19) =====
  "MSG_TYPE_RECORDSV": {
    1: "RECORDSV_RECORDING_START",
    2: "RECORDSV_RECORDING_STOP",
  },

  // ===== MSG_TYPE_LOG_DUMP (20) =====
  "MSG_TYPE_LOG_DUMP": {},

  // ===== MSG_TYPE_LEA_AUDIO (21) =====
  "MSG_TYPE_LEA_AUDIO": {},

  // ===== MSG_TYPE_SYNC_SPP (22) =====
  "MSG_TYPE_SYNC_SPP": {
    1: "OTA_TRANSPORT_SYNC_SPP_DATA_RECV",
    2: "OTA_TRANSPORT_SYNC_SPP_CONN_EVENT",
  },

  // ===== MSG_TYPE_SYNC_BLE (23) =====
  "MSG_TYPE_SYNC_BLE": {
    1: "OTA_TRANSPORT_SYNC_BLE_DATA_RECV",
    2: "OTA_TRANSPORT_SYNC_BLE_CONN_EVENT",
  },

  // ===== MSG_TYPE_SYNC_IAP2 (24) =====
  "MSG_TYPE_SYNC_IAP2": {
    1: "OTA_TRANSPORT_SYNC_IAP2_DATA_RECV",
    2: "OTA_TRANSPORT_SYNC_IAP2_CONN_EVENT",
  },

  // ===== MSG_TYPE_SPATIAL (25) =====
  "MSG_TYPE_SPATIAL": {
    0: "APP_SPATIAL_MSG_ID_INIT",
    1: "APP_SPATIAL_MSG_ID_RECV_PEER_DATA",
    2: "APP_SPATIAL_MSG_ID_SYNC_SPATIAL_AUDIO",
    3: "APP_SPATIAL_MSG_ID_SET_SPATIAL_PARAM",
  },

  // ===== MSG_TYPE_AUDIO_ANC (26) =====
  "MSG_TYPE_AUDIO_ANC": {},

  // ===== MSG_TYPE_GATTC (27) =====
  "MSG_TYPE_GATTC": {
    0: "APP_GATTC_MSG_ID_HANDLE_GATT_STATE_CHANGED",
    1: "APP_GATTC_MSG_ID_DISCOVERY_SERVICE",
    2: "APP_GATTC_MSG_ID_GATT_WRITE_VALUE",
  },

  // ===== MSG_TYPE_VAD (28) =====
  "MSG_TYPE_VAD": {
    0: "APP_VAD_MSGID_ENABLE",
    1: "APP_VAD_MSGID_DISABLE",
    2: "APP_VAD_MSGID_START",
    3: "APP_VAD_MSGID_STOP",
    4: "APP_VAD_MSGID_SESSION_END",
    5: "APP_VAD_MSGID_FORCE_START",
    6: "APP_VAD_MSGID_FORCE_STOP",
    7: "APP_VAD_MSGID_TX_REQ_SEND_DONE",
    8: "APP_VAD_MSGID_TX_REQ_NO_RSP",
    9: "APP_VAD_MSGID_PRI_START_STREAMING",
    10: "APP_VAD_MSGID_HID_ENABLE",
    11: "APP_VAD_MSGID_HID_DISABLE",
    12: "APP_VAD_MSGID_TWS_SYNC",
    13: "APP_VAD_MSGID_VOICE_HIT",
    14: "APP_VAD_MSGID_KWS_HIT",
    15: "APP_VAD_MSGID_HIT_TIMEOUT",
    16: "APP_VAD_MSGID_UNHIT_TIMEOUT",
  },

  // ===== MSG_TYPE_GFPS (29) =====
  "MSG_TYPE_GFPS": {},

  // ===== MSG_TYPE_AUDIO_LOCAL_MUSIC (30) =====
  "MSG_TYPE_AUDIO_LOCAL_MUSIC": {},

  // ===== MSG_TYPE_ALARM (31) =====
  "MSG_TYPE_ALARM": {},

  // ===== MSG_TYPE_IAP2 (32) =====
  "MSG_TYPE_IAP2": {},

  // ===== MSG_TYPE_VIRTUAL_BASS (33) =====
  "MSG_TYPE_VIRTUAL_BASS": {},

  // ===== MSG_TYPE_ADEQ (34) =====
  "MSG_TYPE_ADEQ": {},

  // ===== MSG_TYPE_DRC (35) =====
  "MSG_TYPE_DRC": {},

  // ===== MSG_TYPE_EQ (36) =====
  "MSG_TYPE_EQ": {},

  // ===== MSG_TYPE_CUS_TRANS (37) =====
  "MSG_TYPE_CUS_TRANS": {},

  // ===== MSG_TYPE_TOUCH (39) =====
  "MSG_TYPE_TOUCH": {
    1: "TOUCH_REMOTE_MSG_ID_SET_SLAVE_UPLOAD_ONOFF",
    2: "TOUCH_REMOTE_MSG_ID_SLAVE_SEND_TOUCH_DATA_TO_MASTER",
    3: "TOUCH_AUTO_CALIBRATION_UNWEAR_INIT",
    4: "TOUCH_AUTO_CALIBRATION_INBOX_UPDATA_NV",
    5: "TOUCH_AUTO_CALIBRATION_READ_DATA",
    6: "TOUCH_AUTO_CALIBRATION_SAVE_NV",
    7: "TOUCH_INIT_POWER_DOWN",
    8: "TOUCH_INIT_POWER_UP",
    9: "TOUCH_INIT",
    10: "TOUCH_INIT_IRQ",
    11: "TOUCH_IMU_INIT",
    12: "TOUCH_POWER_ON_REPORT_WEAR_STATUS",
    13: "TOUCH_IRQ_ERROR_HANDLE",
  },

  // ===== MSG_TYPE_USER_BTN (40) =====
  "MSG_TYPE_USER_BTN": {
    0: "UI_SLAVE_BTN_HANDLE",
    1: "UI_WEAR_STATUS_SYN_HANDLE",
    2: "UI_PEER_WEAR_STATUS_UPDATA",
    3: "UI_WEAR_PAUSE_FLAG_UPDATA",
    4: "UI_TAP_STATUS_SYN_HANDLE",
    5: "UI_RESTART_AUTO_POWER_OFF_SYN_HANDLE",
    6: "UI_1S_TIMER_FUNC_HANDLER",
    7: "UI_BTN_SEND_SYNC_STATUS",
    8: "UI_BTN_WEAR_TWS_ROLE_CHANGE",
    9: "UI_BTN_UNWEAR_TWS_ROLE_CHANGE",
    10: "UI_INEAR_WWS_SWITCH",
    11: "UI_BTN_FUN_SYN",
    12: "UI_AI_STATUS_SYN",
  },

  // ===== MSG_TYPE_FACTORY_TEST (41) =====
  "MSG_TYPE_FACTORY_TEST": {
    0x01: "FACOTRY_TEST_REMOTE_MSG_ID_SLAVE_REPORT_SN",
    0x02: "FACOTRY_TEST_REMOTE_MSG_ID_SLAVE_REPORT_PN",
    0x03: "FACOTRY_TEST_REMOTE_MSG_ID_SLAVE_REPORT_SW_VERSION",
    0x04: "FACOTRY_TEST_REMOTE_MSG_ID_SLAVE_REPORT_HW_VERSION",
    0x05: "FACOTRY_TEST_REMOTE_MSG_ID_SLAVE_REPORT_COLOR",
    0x06: "FACOTRY_TEST_REMOTE_MSG_ID_SLAVE_REPORT_BT_NAME",
    0x07: "FACOTRY_TEST_REMOTE_MSG_ID_SLAVE_REPORT_BT_MAC",
    0x08: "FACOTRY_TEST_REMOTE_MSG_ID_SLAVE_REPORT_BATTERY",
    0x09: "FACOTRY_TEST_REMOTE_MSG_ID_SLAVE_REPORT_NTC",
    0x0A: "FACOTRY_TEST_REMOTE_MSG_ID_SLAVE_REPORT_ENC_LIC_VERIFY",
    0x0B: "FACOTRY_TEST_REMOTE_MSG_ID_SLAVE_REPORT_KWS_LIC_VERIFY",
    0x0C: "FACOTRY_TEST_REMOTE_MSG_ID_SLAVE_REPORT_FACTORY_RESET",
    0x0D: "FACOTRY_TEST_REMOTE_MSG_ID_SLAVE_REPORT_SENSOR_COMM",
  },

  // ===== MSG_TYPE_CUS_LIB1~8 (42-49) =====
  "MSG_TYPE_CUS_LIB1": {},
  "MSG_TYPE_CUS_LIB2": {},
  "MSG_TYPE_CUS_LIB3": {},
  "MSG_TYPE_CUS_LIB4": {},
  "MSG_TYPE_CUS_LIB5": {},
  "MSG_TYPE_CUS_LIB6": {},
  "MSG_TYPE_CUS_LIB7": {},
  "MSG_TYPE_CUS_LIB8": {},

  // ===== MSG_TYPE_MAX (50) =====
  "MSG_TYPE_MAX": {},
};

// 反向映射
export const MSG_TYPE_ID_TO_NAME: Record<number, string> = APP_MSG_TYPE_DICT;

export function getMsgString(msgTypeId: number, msgId: number): string {
  const typeName = MSG_TYPE_ID_TO_NAME[msgTypeId];
  if (!typeName) return `unknown_type(${msgTypeId})::${msgId}`;
  
  const innerDict = MSG_ID_MAP[typeName];
  if (!innerDict) return `${typeName}::${msgId}`;
  
  const msgName = innerDict[msgId] || `UNKNOWN_${typeName}_${msgId}`;
  return `${typeName}::${msgName}`;
}

export function getMsgStringByNames(msgTypeName: string, msgId: number): string {
  const innerDict = MSG_ID_MAP[msgTypeName];
  if (!innerDict) return `${msgTypeName}::${msgId}`;
  const msgName = innerDict[msgId] || `UNKNOWN_${msgTypeName}_${msgId}`;
  return `${msgTypeName}::${msgName}`;
}