// src/share/rpcTables.ts

// ========== 模块ID映射 ==========
export const BT_RPC_MODULE: Record<string, number> = {
  "BT_RPC_DC": 0,
  "BT_RPC_AUD": 1,
  "BT_RPC_TWS": 2,
  "BT_RPC_BQB": 3,
  "BT_RPC_SDP": 4,
  "BT_RPC_L2CAP": 5,
  "BT_RPC_RFCOMM": 6,
  "BT_RPC_HFP": 7,
  "BT_RPC_A2DP": 8,
  "BT_RPC_AVRCP": 9,
  "BT_RPC_SPP": 10,
  "BT_RPC_HID": 11,
  "BT_RPC_PAN": 12,
  "BT_RPC_BNEP": 13,
  "BT_RPC_LE": 14,
  "BT_RPC_SMP": 15,
  "BT_RPC_GATT": 16,
  "BT_RPC_GATT_SERVER": 17,
  "BT_RPC_GATT_CLIENT": 18,
  "BT_RPC_ANCS": 19,
  "BT_RPC_AMS": 20,
  "BT_RPC_IAP2": 21,
  "BT_RPC_GA": 22,
  "BT_RPC_MCP": 23,
  "BT_RPC_CCP": 24,
};

// ========== 命令定义接口 ==========
export interface RpcCmdDef {
  name: string;
  index: number;
}

// ========== 所有模块的命令表 ==========
export const MODULE_CMD_TABLES: Record<string, RpcCmdDef[]> = {
  "BT_RPC_DC": [
    { name: "BT_CMD_SET_ENABLED", index: 0 },
    { name: "BT_CMD_IS_ENABLED", index: 1 },
    { name: "BT_CMD_FACTORY_RESET", index: 2 },
    { name: "BT_CMD_GET_VERSION", index: 3 },
    { name: "BT_CMD_GET_LOCAL_ADDR", index: 4 },
    { name: "BT_CMD_SET_LOCAL_NAME", index: 5 },
    { name: "BT_CMD_GET_LOCAL_NAME", index: 6 },
    { name: "BT_CMD_GET_REMOTE_NAME", index: 7 },
    { name: "BT_CMD_CONNECT", index: 8 },
    { name: "BT_CMD_DISCONNECT", index: 9 },
    { name: "BT_CMD_EIR_ADD_UUID16", index: 10 },
    { name: "BT_CMD_EIR_ADD_UUID128", index: 11 },
    { name: "BT_CMD_SET_VISIBILITY", index: 12 },
    { name: "BT_CMD_ENTER_DUT_MODE", index: 13 },
    { name: "BT_CMD_ENTER_FT_MODE", index: 14 },
    { name: "BT_CMD_ENTER_ULP_MODE", index: 15 },
    { name: "BT_CMD_MULTI_CONNECT", index: 16 },
    { name: "BT_CMD_REMOVE_PAIR", index: 17 },
    { name: "BT_CMD_CLEAR_PAIR_LIST", index: 18 },
    { name: "BT_CMD_GET_COD", index: 19 },
    { name: "BT_CMD_SET_COD", index: 20 },
    { name: "BT_CMD_GET_CONNECTED_DEVICES", index: 21 },
    { name: "BT_CMD_GET_CONNECTION_STATE", index: 22 },
    { name: "BT_CMD_GET_LINK_KEY", index: 23 },
    { name: "BT_CMD_GET_PAIRED_DEVICES", index: 24 },
    { name: "BT_CMD_GET_SYNC_TIME", index: 25 },
    { name: "BT_CMD_SET_3M_FEATURE_ENABLE", index: 26 },
    { name: "BT_CMD_SET_CONNECTION_MODE", index: 27 },
    { name: "BT_CMD_SET_CONN_PREEMPTIVE", index: 28 },
    { name: "BT_CMD_SET_GENERAL_CONFIG", index: 29 },
    { name: "BT_CMD_SET_IO_CAPABILITY", index: 30 },
    { name: "BT_CMD_SET_MULTIPOINT_PRIMARY", index: 31 },
    { name: "BT_CMD_SET_PHY_CFG", index: 32 },
    { name: "BT_CMD_SET_RX_GAIN", index: 33 },
    { name: "BT_CMD_SET_TX_PWR_LEVEL", index: 34 },
    { name: "BT_CMD_SET_PAGE_TX_PWR_LVL", index: 35 },
    { name: "BT_CMD_SET_HCI_EVT_REPORT_ENABLED", index: 36 },
    { name: "BT_CMD_SEND_HCI_COMMAND", index: 37 },
    { name: "BT_CMD_SEND_HCI_DATA", index: 38 },
    { name: "BT_CMD_WRITE_EIR_DATA", index: 39 },
    { name: "BT_CMD_SET_PAGE_SCAN_PARAM", index: 40 },
    { name: "BT_CMD_SET_LINK_POLICY", index: 41 },
    { name: "BT_CMD_SET_HW_RELAY_ALLOWED", index: 42 },
    { name: "BT_CMD_SET_AFH_HOST_CHANNEL_CLASSIFICATION", index: 43 },
    { name: "BT_CMD_SET_TRANSPORT_MAX_CREDITS", index: 44 },
    { name: "BT_CMD_SET_LINK_QOS", index: 45 },
  ],
  "BT_RPC_AUD": [
    { name: "BT_CMD_RESET_MEDIA_RAISE_DURATION", index: 0 },
    { name: "BT_CMD_SET_MEDIA_RAISE_DURATION", index: 1 },
    { name: "BT_CMD_SET_BT_TRIGGER_TS", index: 2 },
    { name: "BT_CMD_SET_AUDIO_POLICY_FILTER", index: 3 },
    { name: "BT_CMD_OPEN_UPSTREAM_AUDIO", index: 4 },
    { name: "BT_CMD_CLOSE_UPSTREAM_AUDIO", index: 5 },
    { name: "BT_CMD_STREAM_BREAK_REPORT_SET_ENABLED", index: 6 },
  ],
  "BT_RPC_TWS": [
    { name: "BT_CMD_TWS_GET_STATE", index: 0 },
    { name: "BT_CMD_TWS_SET_ENABLED", index: 1 },
    { name: "BT_CMD_TWS_SET_DEFAULT_ROLE", index: 2 },
    { name: "BT_CMD_TWS_START_PAIR", index: 3 },
    { name: "BT_CMD_TWS_ROLE_SWITCH", index: 4 },
    { name: "BT_CMD_TWS_GET_PEER_ADDR", index: 5 },
    { name: "BT_CMD_TWS_SET_PEER_ADDR", index: 6 },
    { name: "BT_CMD_TWS_SET_TDS_DATA", index: 7 },
    { name: "BT_CMD_TWS_ENTER_SINGLE_MODE", index: 8 },
    { name: "BT_CMD_TWS_DETECT_ENABLE", index: 9 },
    { name: "BT_CMD_SYNC_LED_ACTION", index: 10 },
    { name: "BT_CMD_SET_PERIOD_SYNC_START", index: 11 },
    { name: "BT_CMD_SET_PERIOD_SYNC_UPDATE", index: 12 },
    { name: "BT_CMD_SET_PERIOD_SYNC_STOP", index: 13 },
    { name: "BT_CMD_SEND_SYNC_EVENT", index: 14 },
    { name: "BT_CMD_TWS_SET_WORK_SCENE", index: 15 },
  ],
  "BT_RPC_BQB": [
    { name: "BT_CMD_BQB_PTS_SYN", index: 0 },
    { name: "BT_CMD_BQB_PTS_AVD", index: 1 },
  ],
  "BT_RPC_SDP": [
    { name: "BT_CMD_SDP_ADD_UUID", index: 0 },
    { name: "BT_CMD_SDP_GET_UUID_INDEX", index: 1 },
    { name: "BT_CMD_SDP_REGISTER_RECORD", index: 2 },
  ],
  "BT_RPC_L2CAP": [
    { name: "BT_CMD_L2CAP_GET_STATE", index: 0 },
    { name: "BT_CMD_L2CAP_REGISTER", index: 1 },
    { name: "BT_CMD_L2CAP_CONNECT", index: 2 },
    { name: "BT_CMD_L2CAP_DISCONNECT", index: 3 },
    { name: "BT_CMD_L2CAP_SEND", index: 4 },
    { name: "BT_CMD_L2CAP_SEND_ECHO_REQ", index: 5 },
    { name: "BT_CMD_L2CAP_SEND_ECHO_RSP", index: 6 },
  ],
  "BT_RPC_RFCOMM": [],
  "BT_RPC_HFP": [
    { name: "BT_CMD_HFP_GET_STATE", index: 0 },
    { name: "BT_CMD_HFP_SET_ENABLED", index: 1 },
    { name: "BT_CMD_HFP_CONNECT", index: 2 },
    { name: "BT_CMD_HFP_DISCONNECT", index: 3 },
    { name: "BT_CMD_HFP_SET_FEATURE", index: 4 },
    { name: "BT_CMD_HFP_DIAL", index: 5 },
    { name: "BT_CMD_HFP_SEND_DTMF", index: 6 },
    { name: "BT_CMD_HFP_REDIAL", index: 7 },
    { name: "BT_CMD_HFP_ANSWER", index: 8 },
    { name: "BT_CMD_HFP_REJECT", index: 9 },
    { name: "BT_CMD_HFP_HANGUP", index: 10 },
    { name: "BT_CMD_HFP_ACTIVATE_VOICE_RECOGNITION", index: 11 },
    { name: "BT_CMD_HFP_DEACTIVATE_VOICE_RECOGNITION", index: 12 },
    { name: "BT_CMD_HFP_SCO_ENABLE", index: 13 },
    { name: "BT_CMD_HFP_CONNECT_SCO", index: 14 },
    { name: "BT_CMD_HFP_DISCONNECT_SCO", index: 15 },
    { name: "BT_CMD_HFP_SWITCH_SCO", index: 16 },
    { name: "BT_CMD_HFP_TWC_REJECT_WAITING", index: 17 },
    { name: "BT_CMD_HFP_TWC_RELEASE_ACTIVE_ACCEPT_WAITING", index: 18 },
    { name: "BT_CMD_HFP_TWC_HOLD_ACTIVE_ACCEPT_WAITING", index: 19 },
    { name: "BT_CMD_HFP_TWC_CONFERENCE", index: 20 },
    { name: "BT_CMD_HFP_REPORT_VOLUME", index: 21 },
    { name: "BT_CMD_HFP_REPORT_MIC_VOLUME", index: 22 },
    { name: "BT_CMD_HFP_REPORT_BATTERY_LEVEL", index: 23 },
    { name: "BT_CMD_HFP_SEND_COMMAND", index: 24 },
    { name: "BT_CMD_HFP_GET_CALL_LIST", index: 25 },
  ],
  "BT_RPC_A2DP": [
    { name: "BT_CMD_A2DP_GET_STATE", index: 0 },
    { name: "BT_CMD_A2DP_SET_ENABLED", index: 1 },
    { name: "BT_CMD_A2DP_CODEC_REGISTER", index: 2 },
    { name: "BT_CMD_A2DP_CONNECT", index: 3 },
    { name: "BT_CMD_A2DP_DISCONNECT", index: 4 },
    { name: "BT_CMD_A2DP_SET_BITRATE", index: 5 },
    { name: "BT_CMD_A2DP_NOTIFY_DATA_SILENT", index: 6 },
  ],
  "BT_RPC_AVRCP": [
    { name: "BT_CMD_AVRCP_GET_STATE", index: 0 },
    { name: "BT_CMD_AVRCP_SET_ENABLED", index: 1 },
    { name: "BT_CMD_AVRCP_CONNECT", index: 2 },
    { name: "BT_CMD_AVRCP_DISCONNECT", index: 3 },
    { name: "BT_CMD_AVRCP_PLAY", index: 4 },
    { name: "BT_CMD_AVRCP_PAUSE", index: 5 },
    { name: "BT_CMD_AVRCP_STOP", index: 6 },
    { name: "BT_CMD_AVRCP_FORWARD", index: 7 },
    { name: "BT_CMD_AVRCP_BACKWARD", index: 8 },
    { name: "BT_CMD_AVRCP_REPORT_VOLUME", index: 9 },
    { name: "BT_CMD_AVRCP_GET_PLAY_STATUS", index: 10 },
  ],
  "BT_RPC_SPP": [
    { name: "BT_CMD_SPP_GET_STATE", index: 0 },
    { name: "BT_CMD_SPP_REGISTER", index: 1 },
    { name: "BT_CMD_SPP_REGISTER_UUID128", index: 2 },
    { name: "BT_CMD_SPP_CONNECT", index: 3 },
    { name: "BT_CMD_SPP_DISCONNECT", index: 4 },
    { name: "BT_CMD_SPP_SEND", index: 5 },
    { name: "BT_CMD_SPP_SET_SERVER_CHANNEL_ACCEPTABLE", index: 6 },
  ],
  "BT_RPC_HID": [
    { name: "BT_CMD_BREDR_HID_ENABLE", index: 0 },
    { name: "BT_CMD_BREDR_HID_CONNECT", index: 1 },
    { name: "BT_CMD_BREDR_HID_DISCONNECT", index: 2 },
    { name: "BT_CMD_BREDR_HID_SEND_CMD", index: 3 },
    { name: "BT_CMD_BREDR_HID_SEND_DATA", index: 4 },
  ],
  "BT_RPC_PAN": [
    { name: "BT_CMD_PAN_CONNECT", index: 0 },
    { name: "BT_CMD_PAN_DISCONNECT", index: 1 },
  ],
  "BT_RPC_BNEP": [],
  "BT_RPC_LE": [
    { name: "BT_CMD_LE_SET_ADV_PARAM", index: 0 },
    { name: "BT_CMD_LE_SET_ADV_DATA", index: 1 },
    { name: "BT_CMD_LE_SET_SCAN_RESPONSE", index: 2 },
    { name: "BT_CMD_LE_SET_ADV_ENABLED", index: 3 },
    { name: "BT_CMD_LE_SET_RANDOM_ADDR", index: 4 },
    { name: "BT_CMD_LE_CONN_UPDATE_PARAM_REQ", index: 5 },
    { name: "BT_CMD_LE_CONN_UPDATE_PARAM_RSP", index: 6 },
    { name: "BT_CMD_LE_SET_ADV_TX_PWR_LEVEL", index: 7 },
    { name: "BT_CMD_LE_GET_ADV_TX_PWR_LEVEL", index: 8 },
    { name: "BT_CMD_LE_SET_EXT_ADV_PARAM", index: 9 },
    { name: "BT_CMD_LE_SET_EXT_ADV_DATA", index: 10 },
    { name: "BT_CMD_LE_SET_EXT_ADV_ENABLED", index: 11 },
    { name: "BT_CMD_LE_SET_EXT_SCAN_RESPONSE", index: 12 },
    { name: "BT_CMD_LE_SET_EXT_ADV_RANDOM_ADDR", index: 13 },
    { name: "BT_CMD_LE_ADD_DEV_TO_RESOLVING_LIST", index: 14 },
    { name: "BT_CMD_LE_CLEAR_RESOLVING_LIST", index: 15 },
    { name: "BT_CMD_LE_SET_ADDR_RESOLUTION_ENABLE", index: 16 },
    { name: "BT_CMD_LE_REMOVE_ADV_SET", index: 17 },
    { name: "BT_CMD_LE_CLEAR_ADV_SETS", index: 18 },
    { name: "BT_CMD_LE_ADD_DEV_TO_WHITE_LIST", index: 19 },
    { name: "BT_CMD_LE_SET_PHY", index: 20 },
    { name: "BT_CMD_LE_READ_PHY", index: 21 },
    { name: "BT_CMD_LE_SET_DATA_LENGTH", index: 22 },
    { name: "BT_CMD_LE_CONNECT", index: 23 },
    { name: "BT_CMD_LE_DISCONNECT", index: 24 },
    { name: "BT_CMD_LE_SET_PUBLIC_ADV_ADDR", index: 25 },
    { name: "BT_CMD_LE_CREATE_RPA_ADDR", index: 26 },
    { name: "BT_CMD_LE_SET_RPA_TIMEOUT", index: 27 },
    { name: "BT_CMD_LE_READ_LOCAL_RPA", index: 28 },
    { name: "BT_CMD_LE_SET_SCAN_FILTER_POLICY", index: 29 },
    { name: "BT_CMD_LE_SET_SCAN_PARAM", index: 30 },
    { name: "BT_CMD_LE_SCAN_ENABLE", index: 31 },
    { name: "BT_CMD_LE_SET_EXT_SCAN_PARAM", index: 32 },
    { name: "BT_CMD_LE_EXT_SCAN_ENABLE", index: 33 },
  ],
  "BT_RPC_SMP": [
    { name: "BT_CMD_SMP_GET_ID_ADDR", index: 0 },
    { name: "BT_CMD_SMP_SYNC_SECURITY_INFO", index: 1 },
    { name: "BT_CMD_SMP_CLEAR_SECURITY_INFO", index: 2 },
    { name: "BT_CMD_CTKD_NOTIFY", index: 3 },
    { name: "BT_CMD_LE_SECURITY_REQUEST", index: 4 },
    { name: "BT_CMD_SMP_SEND_AUTH_RSP", index: 5 },
  ],
  "BT_RPC_GATT": [
    { name: "BT_CMD_GATT_EXCHANGE_MTU", index: 0 },
    { name: "BT_CMD_GATT_CONNECT", index: 1 },
    { name: "BT_CMD_GATT_DISCONNECT", index: 2 },
  ],
  "BT_RPC_GATT_SERVER": [
    { name: "BT_CMD_GATT_SERVER_GET_STATE", index: 0 },
    { name: "BT_CMD_GATT_SERVER_SET_ENABED", index: 1 },
    { name: "BT_CMD_GATT_SERVER_REGISTER_SERVICE", index: 2 },
    { name: "BT_CMD_GATT_SERVER_REGISTER_SERVICE_UUID128", index: 3 },
    { name: "BT_CMD_GATT_SERVER_REGISTER_INC_SERVICE", index: 4 },
    { name: "BT_CMD_GATT_SERVER_REGISTER_CHARACTERISTIC", index: 5 },
    { name: "BT_CMD_GATT_SERVER_REGISTER_CHARACTERISTIC_UUID128", index: 6 },
    { name: "BT_CMD_GATT_SERVER_SET_CONN_REQ_ACCEPTABLE", index: 7 },
    { name: "BT_CMD_GATT_SERVER_NOTIFY", index: 8 },
    { name: "BT_CMD_GATT_SERVER_INDICATE", index: 9 },
    { name: "BT_CMD_GATT_SERVER_SEND_READ_RESPONSE", index: 10 },
    { name: "BT_CMD_GATT_SERVER_REGISTER_DONE", index: 11 },
    { name: "BT_CMD_GATT_SERVER_SET_BLE_NAME", index: 12 },
    { name: "BT_CMD_GATT_SERVER_GET_DATAHASH", index: 13 },
    { name: "BT_CMD_GATT_SERVER_SEND_READ_BY_TYPE_RSP", index: 14 },
    { name: "BT_CMD_GATT_SERVER_SEND_WRITE_RESPONSE", index: 15 },
  ],
  "BT_RPC_GATT_CLIENT": [
    { name: "BT_CMD_GATT_CLIENT_GET_STATE", index: 0 },
    { name: "BT_CMD_GATT_CLIENT_DISCOVER_SERVICES_UUID", index: 1 },
    { name: "BT_CMD_GATT_CLIENT_DISCOVER_SERVICES_UUID128", index: 2 },
    { name: "BT_CMD_GATT_CLIENT_DISCOVER_CHARACTER_UUID", index: 3 },
    { name: "BT_CMD_GATT_CLIENT_DISCOVER_CHARACTER_UUID128", index: 4 },
    { name: "BT_CMD_GATT_CLIENT_DISCOVER_DESCRIPTORS", index: 5 },
    { name: "BT_CMD_GATT_CLIENT_READ", index: 6 },
    { name: "BT_CMD_GATT_CLIENT_WRITE", index: 7 },
    { name: "BT_CMD_GATT_CLIENT_READ_BY_TYPE", index: 8 },
  ],
  "BT_RPC_ANCS": [
    { name: "BT_CMD_ANCS_DISCOVER_SERVER", index: 0 },
    { name: "BT_CMD_ANCS_CLOSE_SERVER", index: 1 },
    { name: "BT_CMD_ANCS_GET_NOTIFICATION_ATTR", index: 2 },
    { name: "BT_CMD_ANCS_GET_APP_ATTR", index: 3 },
    { name: "BT_CMD_ANCS_PERFORM_NOTIFICATION_ACTION", index: 4 },
  ],
  "BT_RPC_AMS": [],
  "BT_RPC_IAP2": [
    { name: "BT_CMD_IAP2_CONNECT", index: 0 },
    { name: "BT_CMD_IAP2_DISCONNECT", index: 1 },
    { name: "BT_CMD_IAP2_SEND", index: 2 },
    { name: "BT_CMD_IAP2_CTL_MSG_SEND", index: 3 },
  ],
  "BT_RPC_GA": [
    { name: "BT_CMD_GA_REPORT_VOLUME", index: 0 },
    { name: "BT_CMD_GA_SEND_VOLUME_RSP", index: 1 },
    { name: "BT_CMD_GA_BIS_ENABLE", index: 2 },
    { name: "BT_CMD_GA_BC_SET_TARGET_SRC_ADDR", index: 3 },
    { name: "BT_CMD_GA_BC_CLEAR_RX_LIST", index: 4 },
  ],
  "BT_RPC_MCP": [
    { name: "BT_CMD_MEDIA_PLAY", index: 0 },
    { name: "BT_CMD_MEDIA_PAUSE", index: 1 },
    { name: "BT_CMD_MEDIA_STOP", index: 2 },
    { name: "BT_CMD_MEDIA_PREV", index: 3 },
    { name: "BT_CMD_MEDIA_NEXT", index: 4 },
  ],
  "BT_RPC_CCP": [
    { name: "BT_CMD_CALL_ANSWER", index: 0 },
    { name: "BT_CMD_CALL_REJECT", index: 1 },
    { name: "BT_CMD_CALL_HANGUP", index: 2 },
    { name: "BT_CMD_CALL_TWC_REJECT_WAITING", index: 3 },
    { name: "BT_CMD_CALL_TWC_ACCEPT_WAITING", index: 4 },
  ],
};

// ========== 构建命令ID ==========
export function buildCmdId(module: number, index: number): number {
  return (module << 8) | index;
}